import type { Metadata } from "next";
import { Providers } from "@/utils/providers";
import { HydrateClient, trpc } from "@/utils/ssr";
import "./globals.css";

// La DB puede cambiar en cada request: forzamos render dinámico para que
// el prefetch SSR traiga datos frescos (si no, `/` se prerenderiza estático
// y el prefetch correría una sola vez en build, con datos viejos).
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Prefetch SERVER: llenamos el QueryClient del server ANTES de enviar el
  // HTML (await, porque la DB es async). HydrateClient (server) serializa
  // ese cache con dehydrate y lo viaja al cliente -> cero "Cargando...".
  await trpc.todo.list.prefetchInfinite({ limit: 20 });

  return (
    <html lang="en" className="h-full antialiased">
      <body>
        <HydrateClient>
          <Providers>{children}</Providers>
        </HydrateClient>
      </body>
    </html>
  );
}